### ISSUE TITLE
onDraw loop

### ISSUE THREAD

**Issue by pakerfeldt** [m5/MagicTextView#2]
With the current design, onDraw() is doing stuff that eventually will have the entire view invalidated, thus calling onDraw again and we're stuck in an infinite loop. This widget shouldn't really be used until this is fixed.

**Comment by RoundSparrow** [comment]
FYI: I don't see this problem - tested on Android 4.4 by putting a logcat in the onDraw

**Comment by m5** [comment]
So, this was once an issue, but I'm pretty sure I fixed it. I just hooked up to a profiler, also on 4.4, and everything seemed fine.
