### ISSUE TITLE
License please?

### ISSUE THREAD

**Issue by annas8** [m5/MagicTextView#4]
Yeah this is very nice component for Android. Can you clarify the license of this project? For example;

https://github.com/nicklockwood/FXLabel/blob/master/LICENCE.md

Thanks!

**Comment by m5** [comment]
Sorry, missed this.

Consider it tri-liscenced BSD/MIT/WTFPL.

I'll add liscence docs when I get a chance.

**Comment by annas8** [comment]
Thank you!

**Comment by pjakubczyk** [comment]
hey @m5 is there any change to post the license? I love your component. With AwesomeFont it would really simplify my project and reduce number of pngs :)

**Comment by m5** [comment]
I've added license docs. Use under whichever you like.
