### ISSUE TITLE
Solution for inner shadow problem in new APIs

### ISSUE THREAD

**Issue by Gilianp** [m5/MagicTextView#6]
The problem is that inner shadow are drawn by using PorterDuffXfermode, and many of this operations are not supported be hardware accelerated (new APIs have this as default). So, you should disable hardware acceleration for these type of views.

in init() method you should put:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
    setLayerType(View.LAYER_TYPE_SOFTWARE, null);
}
```

this solved all my problems in all levels of API

**Comment by m5** [comment]
Thanks for the tip, sorry for the delay. This has been added.
