### ISSUE TITLE
strokeWidth should be dimensions

### ISSUE THREAD

**Issue by ismaelorenstein** [m5/MagicTextView#7]
I'm having an issue with strokeWidth being defined as a float - depending on the screen resolution, the text will look different

I guess the easiest solution is to just change it to dimension. On attr.xml:
<attr name="strokeWidth" format="dimension" />

And then on method MagiceTextView.formatMagicTextView:
float strokeWidth = a.getDimension(R.styleable.MagicTextView_strokeWidth, 1);

**Comment by kenyee** [comment]
I'd second this...

**Comment by RoundSparrow** [comment]
Could also consider the density...

```
    final float scale = getContext().getResources().getDisplayMetrics().density;
```

**Comment by m5** [comment]
I've moved the dimension types over to actual dimensions. So, numbers will need a dp/px suffix. Sorry for the delay, it was a good idea.
